# 2017 May 26
# https://docpad.org/docs/deploy
# https://github.com/balupton/awesome-travis
sudo: false
language: node_js
node_js:
- "7"
cache:
  directories:
    - $HOME/.npm  # npm's cache
    - $HOME/.yarn-cache  # yarn's cache
before_script:
- npm run our:verify
after_success:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/deploy-custom.bash)"
notifications:
  slack:
    secure: DhJEwkGg347WIite3EeCOvw7QqehI2fEeDwrtS9ApzYuoLMB1pAl5ZgRi41Kg3H7UxKBLlaY6PAEFY2cp5FuDM+l61srKjO4llP3PrPADujyBweIzkXmvJlelJuJ5kUujh34eWCEkoLbQXHhJup1MHffi24Z9lJV5E+ArhtX7FQ=
  email:
    recipients:
      secure: IcksCZA15d2Aq0SfSWRKDSbe9lJUSci5R60gJYE5kkNKpxfvd34lDiel869V/Xc/0CGlg+qBpaGJERDCnrDOoi+nKC1VAiby8DHJA0eucFpIC95/3iskV+DcnKiV2ulEs6RXzkYlIEwUPWb8o45l2fWaYzabfwPDLz+Q0qyJ+KI=
